version: '3.4'

services:
   catalogdb:
     container_name: catalogdb
     restart: always
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db

   basketdb:
     container_name: basketdb
     restart: always
     ports:
       - "6379:6379"

   discountdb:
     container_name: discountdb
     environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin1234
        - POSTGRES_DB=DiscountDb
     restart: always 
     ports:
        - "5432:5432"
     volumes:
        - postgres_data:/var/lib/postgresql/data/
   
   orderdb:
     container_name: orderdb
     environment:
         - ACCEPT_EULA=Y
         - SA_PASSWORD=Biobihlud100%
     restart: always
     ports:
       - "1433:1433"

   rabbitmq:
     container_name: rabbitmq
     restart: always
     ports:
       - "5672:5672"
       - "15672:15672"

   pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@eShopping.net
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
        
   portainer:
    container_name: portainer
    restart: always
    ports:
      - "7070:8000"
      - "9090:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

   catalog.api:
     container_name: catalog.api
     environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
        - "DatabaseSettings__DatabaseName=CatalogDb"
        - "DatabaseSettings__CollectionName=Products"
        - "DatabaseSettings__BrandsCollection=Brands"
        - "DatabaseSettings__TypesCollection=Types"
        - "ElasticConfiguration__Uri=http://elasticsearch:9200"
     depends_on:
        - catalogdb
     ports:
        - "8080:80"
        - "8081:443"
        
   basket.api:
      container_name: basket.api
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_HTTP_PORTS=8082
        - ASPNETCORE_HTTPS_PORTS=8083 
        - "CacheSettings__ConnectionString=basketdb:6379"
        - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
        - "GrpcSettings__DiscountUrl=http://discount.api"

      depends_on:
          - basketdb
          - rabbitmq
      ports:
        - "8082:80"
        - "8083:443"

   discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=8084
      - ASPNETCORE_HTTPS_PORTS=8085 
      - "DatabaseSettings__ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - discountdb
    ports:
      - "8084:80"
      - "8085:443"

   ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087 
      - "ConnectionStrings__OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=Biobihlud100%"
      - "EventBusSettings__HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8086:80"
      - "8087:443"

volumes:
  mongo_data: