version: '3.4'

services:
   catalogdb:
     container_name: catalogdb
     restart: always
     ports:
       - "27017:27017"
     volumes:
       - mongo_data:/data/db

   catalog.api:
     container_name: catalog.api
     environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
        - "DatabaseSettings__ConnectionString=mongodb://catalogdb:27017"
        - "DatabaseSettings__DatabaseName=CatalogDb"
        - "DatabaseSettings__CollectionName=Products"
        - "DatabaseSettings__BrandsCollection=Brands"
        - "DatabaseSettings__TypesCollection=Types"
        - "ElasticConfiguration__Uri=http://elasticsearch:9200"
     depends_on:
        - catalogdb
     ports:
        - "8080:80"
        - "8081:443"
volumes:
  mongo_data: